name: Deploy para VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Enviar arquivos para a VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/opt/chat"
          overwrite: true

            - name: Rodar comandos remotos (instalar dependências e extrair ZIP)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/chat
            apt-get update -y && apt-get install -y unzip  # garante que o unzip esteja disponível
            unzip -o downloand_novoinstaladordigitalzapzip.zip -d .
            chmod +x *.sh

